### ISSUE TITLE
Which zip file?

### ISSUE THREAD

**Issue by scholarsgrotto** [dhsouthbend/mapping#1]
On [this page](https://github.com/dhsouthbend/mapping/blob/master/sections/2setup.md), which zip file are we supposed to be working with? The one at CUNY, as currently pointed to, or the one stored on the local dhsouthbend repo? They are similar, but not identical, and I don't know which is more up to date.

**Comment by akrgrant** [comment]
Thanks for catching this! I updated the link on that page to the updated zip file I created on the local dhsouthbend repo.

**Comment by scholarsgrotto** [comment]
Awesome, thanks!
